# Site settings
title: datanaut
email: christopher.r.zhou@gmail.com
description: Exploring, discovering and "charting" the Dataverse
url: ""
username: chrisrzhou
include: ["_pages"]

category: [visualizations, tutorials, other, site, tags, archive]
collections:
  about:
    output: false
  blog:
    output: true
  projects:
    output: true
  resume:
    output: false

# Build settings
timezone: America/Houston
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /blog/:categories/:year/:month/:day/:title
